dist: xenial
language: python

cache: pip

branches:
  only:
    - master

matrix:
  include:
    - python: 3.7
      env: NOX_SESSION=check
    - python: 3.7
      env: NOX_SESSION=docs

    - python: 3.6
      env: NOX_SESSION=test-3.6
    - python: 3.7
      env: NOX_SESSION=test-3.7
    - python: 3.8-dev
      env: NOX_SESSION=test-3.8
      dist: bionic # Required to get OpenSSL 1.1.1+

  # Allow builds to fail when using '-dev' Python versions
  # Should still investigate failures periodically for new APIs.
  fast_finish: true
  allow_failures:
    - python: 3.8-dev

install:
  - pip install --upgrade nox

script:
  - nox -s ${NOX_SESSION}

after_script:
  - if [ -f .coverage ]; then
      python -m pip install codecov;
      codecov --required;
    fi
