dist: xenial
language: python

cache: pip

branches:
  only:
    - master

python:
  - 3.6
  - 3.7
  - 3.8

stages:
  - check
  - docs
  - test

matrix:
  include:
    -
      stage: check
      python: 3.7
      script: scripts/check
    - stage: docs
      python: 3.7
      script: scripts/docs-build
    - stage: test
      os: windows
      language: shell
      python: 3.7
      env:
        PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
      install: pip install -r requirements.txt
      script: scripts/test

  fast_finish: true
  allow_failures:
    # FIX
    # Some tests not yet resolved for Windows. (In progress)
    - os: windows

script: scripts/test

after_script:
  - if [ -f .coverage ]; then
      python -m pip install codecov;
      codecov --required;
    fi
