site_name: HTTPX
site_description: A next-generation HTTP client for Python.
site_url: https://www.python-httpx.org/

theme:
    name: 'material'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'blue'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'

repo_name: encode/httpx
repo_url: https://github.com/encode/httpx/
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - QuickStart: 'quickstart.md'
    - Command Line Client: 'command-line-client.md'
    - Clients:
        - Overview: 'clients/overview.md'
        - Authentication: 'clients/authentication.md'
        - Redirects: 'clients/redirects.md'
        - Cookies: 'clients/cookies.md'
        - SSL: 'clients/ssl.md'
        - Proxies: 'clients/proxies.md'
        - Timeouts: 'clients/timeouts.md'
        - HTTP Version: 'clients/http-version.md'
        - Event Hooks: 'clients/event-hooks.md'
        - Building Requests: 'clients/building-requests.md'
    - Requests and Responses:
        - Requests: 'models/requests.md'
        - Responses: 'models/responses.md'
        - URLs: 'models/urls.md'
        - Headers: 'models/headers.md'
        - Status Codes: 'models/status_codes.md'
        - Extensions: 'models/extensions.md'
    - Transports:
        - Overview: 'transports/index.md'
        - HTTP: 'transports/http.md'
        - WSGI: 'transports/wsgi.md'
        - ASGI: 'transports/asgi.md'
        - Mounts: 'transports/mounts.md'
        - Mock: 'transports/mock.md'
        - Custom: 'transports/custom.md'
    - Topics:
        - HTTPX Version 1.0: 'topics/httpx-1.0.md'
        - Requests Compatability: 'topics/requests-compat.md'
        - Logging: topics/logging.md
        - WebSockets: topics/websockets.md
        - Server Sent Events: topics/server-sent-events.md
    - Community:
        - Third Party Packages: 'community/third_party_packages.md'
        - Contributing: 'community/contributing.md'
        - Code of Conduct: 'community/code_of_conduct.md'

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc

extra_css:
    - css/custom.css
